import type { NextPage } from 'next'
import Head from 'next/head'
import useSWR, { Fetcher } from 'swr'
import Blog from '../models/blog'
import Button from '../components/button'
import styled from 'styled-components'
import { StyledContainer, StyledSpan, color } from '../styles'

const Container = styled(StyledContainer)`
  padding: 0 2rem;
  user-select: none;
`

const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const Title = styled.h1`
  margin: 0 0 3rem 0;
  line-height: 1.15;
  font-size: 4rem;
  text-shadow: 0 0 2px ${color};
`

const Author = styled(StyledSpan)`
  text-shadow: 0 0 4px ${color};
`

const Home: NextPage = () => {

  const fetcher: Fetcher<Blog[]> = (url: string) => fetch(url).then(res => res.json());

  const { data } = useSWR<Blog[]>('api/blogs', fetcher)

  if (!data) {
    return <p>Loading...</p>
  }

  return (
    <Container>
      <Head>
        <title>Author.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to <Author variant='primary'>Author.io</Author>
        </Title>
        <Button variant='primary'>Get Started</Button>
      </Main>
    </Container>
  )
}

export default Home
